# Generated by Django 5.0.6 on 2024-08-09 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0004_commentbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 5, 2, 49, 15932, tzinfo=datetime.timezone.utc)),
        ),
    ]
