# Generated by Django 5.0.6 on 2024-08-09 05:49

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0005_alter_rental_return_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='estimated_wait_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 5, 49, 10, 671550, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='rental',
            unique_together={('book', 'user', 'is_returned')},
        ),
    ]
